spring:
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:/webapp/

#server:
#  servlet:
#    context-path: /mall

# mybatis
mybatis:
  mapper-locations: classpath:cn/wwinter/mapper/*.xml,classpath*:cn/wwinter/mapper/*.xml

# pagehelper
pagehelper:
  helper-dialect: mysql
  autoDialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true

logging:
  level:
    root: info
    cn:
      wwinter:
        malldemo: debug

jwt:
  tokenHeader: Authorization
  secret: mySecret243982847650849ovsildfbvf
  expiration: 604800
  tokenHead: "Bearer "

