spring:
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:/webapp/
server:
  port: 8081

# pagehelper
pagehelper:
  helper-dialect: mysql
  autoDialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true

logging:
  level:
    root: info
    cn:
      wwinter:
        malldemo: debug

jwt:
  tokenHeader: Authorization
  tokenHead: "Bearer "
  expiration: 604800
  secret: mySecret-iauysdgfb7yi8t7radsfafr43*&^$%gsadfg897qinwyehd87wegyuhd87wieguh


mybatis:
  mapperLocations: classpath:cn/wwinter/malladmin/mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:cn/wwinter/malladmin/mapper/*.xml

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: test
    accessKeySecret: test
    bucketName: macro-oss
    policy: expire=300
    maxSize: 10
    callback: http://localhost:8080/aliyun/oss/callback
    dir: prefix=mall/images/