spring:
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:/webapp/

# pagehelper
pagehelper:
  helper-dialect: mysql
  autoDialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true

logging:
  level:
    root: info
    cn:
      wwinter:
        malldemo: debug

jwt:
  tokenHeader: Authorization
  secret: mySecret-diaushfoaiuydsgfha328947826&^%*^SUDHJVvygiashdf7q
  expiration: 604800
  tokenHead: "Bearer "


mybatis:
  mapperLocations: classpath:cn/wwinter/malladmin/mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:cn/wwinter/malladmin/mapper/*.xml
