version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es01
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=root
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
      - ./http_ca.crt:/usr/share/elasticsearch/config/certs/http_ca.crt

networks:
  elastic:
    driver: bridge
